using UnityEngine;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FogClouds
{
    // The full, live server-side state for one player.
    // Never sent to clients directly — clients receive a fog-filtered ClientGameStateView.
    // Opponent information is always served from TurnStartSnapshot, not from this object.
    [Serializable]
    public class PlayerState
    {
        //Identity
        //0 or 1
        public int PlayerId;

        //The character this player is playing. Immutable after game start.
        public CharacterData Character;

        //Vitals
        //Current HP. Game ends when this reaches 0. Baseline: 50.
        public int HP;

        //Current shield value. Absorbs incoming damage before HP is reduced.
        public int Shield;

        //Flag for shield carry over (This run could use Calipers)
        public bool ShieldCarriesOver;

        //Deck
        public List<CardInstance> Hand;
        public List<CardInstance> Deck;
        public List<CardInstance> Discard;

        //Board
        //Active permanents and creatures on this player's board.
        public List<BoardPermanent> Board;

        //Active passive abilities (from Permanent-type cards or upgrades).
        public List<Passive> Passives;

        //Resources
        public ResourceState Resources;

        //Status Effects
        public List<StatusEffect> StatusEffects;

        // Universal currency. Earned through card effects only — not auto-generated.
        // Spent at shops and auctions during milestone roguelike events.
        public int Silver;

        //Fog
        // This player's fog reveal flags — what they can see about their opponent.
        // Set by INSIGHT tree unlocks and card effects. Server-side only.

        public FogRevealState FogReveals;

        //This player's progress through the INSIGHT tech tree.
        public InsightTreeState InsightTree;

        //Roguelike
        //Pre-generated upcoming roguelike offers for this player.
        public RoguelikeOffers UpcomingOffers;

        //Turn Flow
        //Set to true when this player submits an EndTurnIntent during MainPhase.
        public bool ReadyToEndTurn;

        //Set to true when this player has submitted their roguelike upgrade choice.
        public bool UpgradeChoiceSubmitted;

        //Snapshot
        // Frozen copy of the OPPONENT's state, taken at the TurnStart → MainPhase transition.
        // The fog filter reads exclusively from this. Never from the opponent's live PlayerState.
        // Generated by GameState.TakeSnapshots() at the start of each main phase.
        public PlayerSnapshot TurnStartSnapshot;

        //Constructor
        public PlayerState() { }

        public PlayerState(int playerId, CharacterData character)
        {
            PlayerId = playerId;
            Character = character;
            HP = character.BaseHP;
            Shield = 0;
            ShieldCarriesOver = false;
            Silver = 0;

            Hand = new List<CardInstance>();
            Deck = new List<CardInstance>();
            Discard = new List<CardInstance>();
            Board = new List<BoardPermanent>();
            Passives = new List<Passive>();
            StatusEffects = new List<StatusEffect>();

            Resources = new ResourceState(character.BasePerTurnResourceMax);
            FogReveals = new FogRevealState(); // all false = full fog
            InsightTree = new InsightTreeState();
            UpcomingOffers = new RoguelikeOffers();

            ReadyToEndTurn = false;
            UpgradeChoiceSubmitted = false;
            TurnStartSnapshot = null; // set at first MainPhase begin
        }

        //Helpers - only functions that require no external context should live here.
        // Resets per-turn state at TurnStart. Called before drawing cards.
        public void OnTurnStart()
        {
            Resources.RefreshPerTurn();
            if (!ShieldCarriesOver) Shield = 0;
            ReadyToEndTurn = false;
            UpgradeChoiceSubmitted = false;
        }

        // Returns true if this player is alive.
        public bool IsAlive => HP > 0;

        // Applies damage to this player, reducing shield first then HP.
        // Only callable if the attacker has CharacterIdentity revealed (enforced by GameManager).
        public void TakeDamage(int amount)
        {
            int shieldAbsorb = Math.Min(Shield, amount);
            Shield -= shieldAbsorb;
            HP -= amount - shieldAbsorb;
            HP = Math.Max(HP, 0);
        }

        // Adds shield to this player, typically from a card effect.
        public void GainShield(int amount)
        {
            Shield += amount;
        }

        public void ApplyStatusEffect(StatusEffect effect)
        {
            // If the effect already exists, refresh or stack it depending on design
            var existing = StatusEffects.FirstOrDefault(e => e.EffectId == effect.EffectId);
            if (existing != null)
                existing.Duration = Math.Max(existing.Duration, effect.Duration);
            else
                StatusEffects.Add(effect);
        }

        public void TickStatusEffects()
        {
            foreach (var e in StatusEffects)
                if (e.Duration > 0) e.Duration--;
            StatusEffects.RemoveAll(e => e.Duration == 0);
        }

        // Shuffles the deck using the server RNG
        public void ShuffleDeck(System.Random rng)
        {
            for (int i = Deck.Count - 1; i > 0; i--)
            {
                int j = rng.Next(i + 1);
                var temp = Deck[i];
                Deck[i] = Deck[j];
                Deck[j] = temp;
            }
        }

        // Draws n cards from the deck into hand.
        // If deck is empty, reshuffles discard first.
        // If both are empty, does nothing.
        public void DrawCards(int count, System.Random rng)
        {
            for (int i = 0; i < count; i++)
            {
                if (Deck.Count == 0)
                {
                    if (Discard.Count == 0)
                    {
                        Debug.LogWarning($"[PlayerState] Player {PlayerId} has no cards left to draw.");
                        return;
                    }
                    Deck.AddRange(Discard);
                    Discard.Clear();
                    ShuffleDeck(rng);
                    Debug.Log($"[PlayerState] Player {PlayerId} reshuffled discard into deck.");
                }

                var card = Deck[0];
                Deck.RemoveAt(0);
                Hand.Add(card);
            }
        }

        // Moves a card from hand to discard after it is played.
        public void DiscardCard(CardInstance card)
        {
            Hand.Remove(card);
            Discard.Add(card);
        }
    }

    // A status effect applied to a QueueEntry.
    // Stub for Phase 0 — effect logic implemented in Phase 3+.

    [Serializable]
    public class StatusEffect
    {
        public string EffectId;
        public int Value;
        public int Duration; // in resolution steps; -1 = permanent for this turn

        public StatusEffect() { }

        public StatusEffect(string effectId, int value, int duration = 1)
        {
            EffectId = effectId;
            Value = value;
            Duration = duration;
        }
    }
}
